services:
    eureukaserver:
      build:
        dockerfile: "./Dockerfiles/eureukaserver.Dockerfile"
      ports: 
        - 9091:9091
      networks:
        - sharednetwork

    microservice1:
      build:
        dockerfile: "./Dockerfiles/microservice1.Dockerfile"
      ports: 
        - 9090:9090
      networks:
        - sharednetwork
    
    microservice2:
      build:
        dockerfile: "./Dockerfiles/microservice2.Dockerfile"
      ports: 
        - 8081:8081
      networks:
        - sharednetwork

    dbCommand:
      ports: 
        - 5432:5432
      build:
        dockerfile: "./Dockerfiles/dbCommand.Dockerfile"
      networks:
        - sharednetwork
    dbFournisseurs:
      ports: 
        - 5433:5433
      build:
        dockerfile: "./Dockerfiles/dbFournisseurs.Dockerfile"
      networks:
        - sharednetwork
    apigatewayzuul:
      ports: 
        - 8765:8765
      build:
        dockerfile: "./Dockerfiles/zuulgateway.Dockerfile"
      networks:
        - sharednetwork

networks:
  sharednetwork:{}